name: Bug report
description: Create a bug report to help improve 2FAuth
projects: Bubka/1
body:
  - type: input
    id: 2fauth_version
    attributes:
      label: 2FAuth version
      description: The 2FAuth version on which the issue occurs
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Details & Steps to reproduce
      description: A clear and concise description of what happens and how to reproduce it. Screenshots are welcome.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: A  description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: error_logs
    attributes:
      label: Error & Logs
      description: >-
        Error message, stack traces, error/access logs from apache/NGINX, php or
        your database system.
      placeholder: 2FAuth logs can be found in [2FAuth_install_directory]/storage/logs/
      render: shell
  - type: textarea
    id: environment
    attributes:
      label: Execution environment
      description: How do you run and access 2FAuth and how it is configured
      placeholder: >-
        Server side: http server, db system, php version,etc...&#10;
        client side: Desktop? Mobile? Device model, OS name:version, Browser name:version
        &#10;
        The /about page of your 2FAuth instance displays environment variables,
        user preferences and admin settings you can easily copy and past here.
  - type: checkboxes
    id: context
    attributes:
      label: Containerization
      options:
        - label: Docker
          required: false
  - type: textarea
    id: client
    attributes:
      label: Client
      description: Details on your client device.
      placeholder: Desktop? Mobile? Device model, OS name:version, Browser name:version
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information
      description: Any additional information you would like to submit
